#
# full text search
#
## CBO - Descrição - Total

import re

# lista de profissoes (CBO)
lst_profissoes = [ 'ACOUGUEIRO', 
                   'ACROBATA', 
                   'ADMINISTRADOR', 
                   'ADMINISTRADOR DE BANCO DE DADOS', 
                   'ADMINISTRADOR DE REDES', 
                   'ADMINISTRADOR DE SISTEMAS OPERACIONAIS', 
                   'ADMINISTRADOR EM SEGURANCA DA INFORMACAO', 
                   'ADVOGADO', 
                   'AGENTE COMUNITARIO DE SAUDE', 
                   'AGENTE DE ACAO SOCIAL', 
                   'AGENTE DE COMBATE AS ENDEMIAS', 
                   'AGENTE DE DEFESA AMBIENTAL', 
                   'AGENTE DE HIGIENE E SEGURANCA', 
                   'AGENTE DE MANOBRA E DOCAGEM', 
                   'AGENTE DE MICROCREDITO', 
                   'AGENTE DE PATIO', 
                   'AGENTE DE SAUDE PUBLICA', 
                   'AGENTE DE SEGURANCA', 
                   'AGENTE DE VENDAS DE SERVICOS', 
                   'AGENTE FISCAL DE QUALIDADE', 
                   'AGENTE INDIGENA DE SANEAMENTO', 
                   'AGENTE INDIGENA DE SAUDE', 
                   'AJUDANTE DE MOTORISTA', 
                   'AJUSTADOR MECANICO', 
                   'ALMOXARIFE', 
                   'ANALISTA DE DESENVOLVIMENTO DE SISTEMAS', 
                   'ANALISTA DE INFORMACOES (PESQUISADOR DE INFORMACOES DE REDE)', 
                   'ANALISTA DE PESQUISA DE MERCADO', 
                   'ANALISTA DE PLANEJAMENTO E ORCAMENTO APO', 
                   'ANALISTA DE RECURSOS HUMANOS', 
                   'ANALISTA DE REDES E DE COMUNICACAO DE DADOS', 
                   'ANALISTA DE SISTEMAS DE AUTOMACAO', 
                   'ANALISTA DE SUPORTE COMPUTACIONAL', 
                   'ANALISTA FINANCEIRO (INSTITUICOES FINANCEIRAS)', 
                   'ARQUITETO DE EDIFICACOES', 
                   'ARQUITETO DE PATRIMONIO', 
                   'ARQUITETO URBANISTA', 
                   'ARQUIVISTA', 
                   'ARQUIVISTA DE DOCUMENTOS', 
                   'ARTESAO BORDADOR', 
                   'ARTESAO CERAMISTA', 
                   'ARTESAO COM MATERIAL RECICLAVEL', 
                   'ARTESAO CONFECCIONADOR DE BIOJOIAS E ECOJOIAS', 
                   'ARTESAO ESCULTOR', 
                   'ARTESAO TECELAO', 
                   'ARTESAO TRICOTEIRO', 
                   'ARTETERAPEUTA', 
                   'ARTIFICE DO COURO', 
                   'ARTISTA (ARTES VISUAIS)', 
                   'ASCENSORISTA', 
                   'ASSESSOR DE IMPRENSA', 
                   'ASSISTENTE ADMINISTRATIVO', 
                   'ASSISTENTE SOCIAL', 
                   'ATENDENTE DE ENFERMAGEM', 
                   'ATENDENTE DE FARMACIA BALCONISTA', 
                   'ATENDENTE DE JUDICIARIO', 
                   'ATENDENTE DE LAVANDERIA', 
                   'AUDITOR (CONTADORES E AFINS)', 
                   'AUXILIAR DE BANCO DE SANGUE', 
                   'AUXILIAR DE BIBLIOTECA', 
                   'AUXILIAR DE CONTABILIDADE', 
                   'AUXILIAR DE DESENVOLVIMENTO INFANTIL', 
                   'AUXILIAR DE ENFERMAGEM', 
                   'AUXILIAR DE ENFERMAGEM DA ESTRATEGIA DE SAUDE DA FAMILIA', 
                   'AUXILIAR DE ENFERMAGEM DO TRABALHO', 
                   'AUXILIAR DE ESCRITORIO, EM GERAL', 
                   'AUXILIAR DE ESTATISTICA', 
                   'AUXILIAR DE FARMACIA DE MANIPULACAO', 
                   'AUXILIAR DE FATURAMENTO', 
                   'AUXILIAR DE LABORATORIO DE ANALISES CLINICAS', 
                   'AUXILIAR DE LABORATORIO DE ANALISES FISICOQUIMICAS', 
                   'AUXILIAR DE LABORATORIO DE IMUNOBIOLOGICOS', 
                   'AUXILIAR DE LAVANDERIA', 
                   'AUXILIAR DE MANUTENCAO PREDIAL', 
                   'AUXILIAR DE PESSOAL', 
                   'AUXILIAR DE PRODUCAO FARMACEUTICA', 
                   'AUXILIAR DE PROTESE DENTARIA', 
                   'AUXILIAR DE RADIOLOGIA (REVELACAO FOTOGRAFICA)', 
                   'AUXILIAR DE SERVICOS JURIDICOS', 
                   'AUXILIAR DE VETERINARIO', 
                   'AUXILIAR EM SAUDE BUCAL', 
                   'AUXILIAR EM SAUDE BUCAL DA ESTRATEGIA DE SAUDE DA FAMILIA', 
                   'AUXILIAR GERAL DE CONSERVACAO DE VIAS PERMANENTES (EXCETO TRILHOS)', 
                   'AUXILIAR NOS SERVICOS DE ALIMENTACAO', 
                   'AUXILIAR TECNICO EM LABORATORIO DE FARMACIA', 
                   'AUXILIAR TECNICO EM PATOLOGIA CLINICA', 
                   'AVALIADOR FISICO', 
                   'BIBLIOTECARIO', 
                   'BIOENGENHEIRO', 
                   'BIOLOGO', 
                   'BIOMEDICO', 
                   'CABELEIREIRO', 
                   'CARPINTEIRO', 
                   'CHEFE DE CONTABILIDADE (TECNICO)', 
                   'CHEFE DE COZINHA', 
                   'CICLISTA MENSAGEIRO', 
                   'CIRURGIAO DENTISTA AUDITOR', 
                   'CIRURGIAO DENTISTA CLINICO GERAL', 
                   'CIRURGIAO DENTISTA DENTISTICA', 
                   'CIRURGIAO DENTISTA ENDODONTISTA', 
                   'CIRURGIAO DENTISTA EPIDEMIOLOGISTA', 
                   'CIRURGIAO DENTISTA ESTOMATOLOGISTA', 
                   'CIRURGIAO DENTISTA IMPLANTODONTISTA', 
                   'CIRURGIAO DENTISTA ODONTOGERIATRA', 
                   'CIRURGIAO DENTISTA ODONTOLOGIA DO TRABALHO', 
                   'CIRURGIAO DENTISTA ODONTOLOGIA PARA PACIENTES COM NECESSIDADES ESPECIAIS', 
                   'CIRURGIAO DENTISTA ODONTOLOGISTA LEGAL', 
                   'CIRURGIAO DENTISTA ODONTOPEDIATRA', 
                   'CIRURGIAO DENTISTA ORTOPEDISTA E ORTODONTISTA', 
                   'CIRURGIAO DENTISTA PATOLOGISTA BUCAL', 
                   'CIRURGIAO DENTISTA PERIODONTISTA', 
                   'CIRURGIAO DENTISTA PROTESIOLOGO BUCOMAXILOFACIAL', 
                   'CIRURGIAO DENTISTA PROTESISTA', 
                   'CIRURGIAO DENTISTA RADIOLOGISTA', 
                   'CIRURGIAO DENTISTA REABILITADOR ORAL', 
                   'CIRURGIAO DENTISTA TRAUMATOLOGISTA BUCOMAXILOFACIAL', 
                   'CIRURGIAO DENTISTA DE SAUDE COLETIVA', 
                   'CIRURGIAODENTISTA DA ESTRATEGIA DE SAUDE DA FAMILIA', 
                   'CITOTECNICO', 
                   'COBRADOR EXTERNO', 
                   'COLETOR DE LIXO DOMICILIAR', 
                   'COLETOR DE RESIDUOS SOLIDOS DE SERVICOS DE SAUDE', 
                   'COMPRADOR', 
                   'CONDUTOR DE AMBULANCIA', 
                   'CONDUTOR DE VEICULOS DE TRACAO ANIMAL (RUAS E ESTRADAS)', 
                   'CONFERENTEEXPEDIDOR DE ROUPAS (LAVANDERIAS)', 
                   'CONSULTOR CONTABIL (TECNICO)', 
                   'CONSULTOR JURIDICO', 
                   'CONTADOR', 
                   'CONTINUO', 
                   'CONTROLADOR DE ENTRADA E SAIDA', 
                   'CONTROLADOR DE PRAGAS', 
                   'COORDENADOR PEDAGOGICO', 
                   'COPEIRO', 
                   'COPEIRO DE HOSPITAL', 
                   'COSTUREIRA DE REPARACAO DE ROUPAS', 
                   'COSTUREIRO NA CONFECCAO EM SERIE', 
                   'COZINHADOR (CONSERVACAO DE ALIMENTOS)', 
                   'COZINHEIRO DE HOSPITAL', 
                   'COZINHEIRO GERAL', 
                   'CROCHETEIRO, A MAO', 
                   'CUIDADOR DE IDOSOS', 
                   'CUIDADOR EM SAUDE', 
                   'DANCARINO POPULAR', 
                   'DESENHISTA INDUSTRIAL (DESIGNER)', 
                   'DESENHISTA PROJETISTA DE ARQUITETURA', 
                   'DESENHISTA TECNICO (ARQUITETURA)', 
                   'DIETISTA', 
                   'DIGITADOR', 
                   'DIRETOR ADMINISTRATIVO', 
                   'DIRETOR ADMINISTRATIVO E FINANCEIRO', 
                   'DIRETOR DE INSTITUICAO EDUCACIONAL DA AREA PRIVADA', 
                   'DIRETOR DE INSTITUICAO EDUCACIONAL PUBLICA', 
                   'DIRETOR DE MANUTENCAO', 
                   'DIRETOR DE OPERACOES DE SERVICOS DE TRANSPORTE', 
                   'DIRETOR DE PESQUISA E DESENVOLVIMENTO (PD)', 
                   'DIRETOR DE PLANEJAMENTO ESTRATEGICO', 
                   'DIRETOR DE RECURSOS HUMANOS', 
                   'DIRETOR DE RELACOES DE TRABALHO', 
                   'DIRETOR DE SERVICOS DE INFORMATICA', 
                   'DIRETOR DE SERVICOS DE SAUDE', 
                   'DIRETOR DE SERVICOS SOCIAIS', 
                   'DIRETOR DE SUPRIMENTOS', 
                   'DIRETOR FINANCEIRO', 
                   'DIRETOR GERAL DE EMPRESA E ORGANIZACOES (EXCETO DE INTERESSE PUBLICO)', 
                   'DIRIGENTE DO SERVICO PUBLICO ESTADUAL E DISTRITAL', 
                   'DIRIGENTE DO SERVICO PUBLICO FEDERAL', 
                   'DIRIGENTE DO SERVICO PUBLICO MUNICIPAL', 
                   'DIRIGENTE E ADMINISTRADOR DE ORGANIZACAO DA SOCIEDADE CIVIL SEM FINS LUCRATIVOS', 
                   'DOULA', 
                   'ECONOMISTA', 
                   'ECONOMISTA DO SETOR PUBLICO', 
                   'ECONOMISTA FINANCEIRO', 
                   'EDUCADOR SOCIAL', 
                   'ELETRICISTA DE INSTALACOES', 
                   'ELETRICISTA DE INSTALACOES (EDIFICIOS)', 
                   'ELETRICISTA DE MANUTENCAO DE LINHAS ELETRICAS, TELEFONICAS E DE COMUNICACAO DE DADOS', 
                   'ELETRICISTA DE MANUTENCAO ELETROELETRONICA', 
                   'ELETROTECNICO', 
                   'ELETROTENICO NA FABRICACAO, MONTAGEM E INSTALACAO DE MAQUINAS E EQUIPAMENTOS', 
                   'EMPREGADO DOMESTICO FAXINEIRO', 
                   'EMPREGADO DOMESTICO NOS SERVICOS GERAIS', 
                   'ENCANADOR', 
                   'ENCARREGADO DE MANUTENCAO DE INSTRUMENTOS DE CONTROLE, MEDICAO E SIMILARES', 
                   'ENCARREGADO DE MANUTENCAO MECANICA DE SISTEMAS OPERACIONAIS', 
                   'ENCARREGADO GERAL DE OPERACOES DE CONSERVACAO DE VIAS PERMANENTES (EXCETO TRILHOS)', 
                   'ENFERMEIRO', 
                   'ENFERMEIRO AUDITOR', 
                   'ENFERMEIRO DA ESTRATEGIA DE SAUDE DA FAMILIA', 
                   'ENFERMEIRO DE CENTRO CIRURGICO', 
                   'ENFERMEIRO DE TERAPIA INTENSIVA', 
                   'ENFERMEIRO DO TRABALHO', 
                   'ENFERMEIRO ESTOMATERAPEUTA', 
                   'ENFERMEIRO NEFROLOGISTA', 
                   'ENFERMEIRO NEONATOLOGISTA', 
                   'ENFERMEIRO OBSTETRICO', 
                   'ENFERMEIRO PSIQUIATRICO', 
                   'ENFERMEIRO PUERICULTOR E PEDIATRICO', 
                   'ENFERMEIRO SANITARISTA', 
                   'ENGENHEIRO AGRONOMO', 
                   'ENGENHEIRO AMBIENTAL', 
                   'ENGENHEIRO CIVIL', 
                   'ENGENHEIRO CIVIL (SANEAMENTO)', 
                   'ENGENHEIRO DE ALIMENTOS', 
                   'ENGENHEIRO DE CONTROLE E AUTOMACAO', 
                   'ENGENHEIRO DE PRODUCAO', 
                   'ENGENHEIRO DE SEGURANCA DO TRABALHO', 
                   'ENGENHEIRO ELETRICISTA', 
                   'ENGENHEIRO ELETRICISTA DE MANUTENCAO', 
                   'ENGENHEIRO ELETRONICO DE PROJETOS', 
                   'ENGENHEIRO MECANICO', 
                   'ENGENHEIRO QUIMICO', 
                   'ENGENHEIRO QUIMICO (INDUSTRIA QUIMICA)', 
                   'ESTATISTICO', 
                   'ESTERILIZADOR DE ALIMENTOS', 
                   'ESTETICISTA', 
                   'FARMACEUTICO', 
                   'FARMACEUTICO ANALISTA CLINICO', 
                   'FARMACEUTICO EM SAUDE PUBLICA', 
                   'FARMACEUTICO HOSPITALAR E CLINICO', 
                   'FAXINEIRO', 
                   'FISCAL DE ATIVIDADES URBANAS', 
                   'FISCAL DE TRIBUTOS MUNICIPAL', 
                   'FISICO', 
                   'FISICO (MEDICINA)', 
                   'FISICO (NUCLEAR E REATORES)', 
                   'FISIOTERAPEUTA ACUPUNTURISTA', 
                   'FISIOTERAPEUTA DO TRABALHO', 
                   'FISIOTERAPEUTA ESPORTIVO', 
                   'FISIOTERAPEUTA GERAL', 
                   'FISIOTERAPEUTA NEUROFUNCIONAL', 
                   'FISIOTERAPEUTA OSTEOPATA', 
                   'FISIOTERAPEUTA QUIROPRAXISTA', 
                   'FISIOTERAPEUTA RESPIRATORIA', 
                   'FISIOTERAPEUTA TRAUMATOORTOPEDICA FUNCIONAL', 
                   'FONOAUDIOLOGO', 
                   'FONOAUDIOLOGO EDUCACIONAL', 
                   'FONOAUDIOLOGO EM AUDIOLOGIA', 
                   'FONOAUDIOLOGO EM LINGUAGEM', 
                   'GERENTE ADMINISTRATIVO', 
                   'GERENTE COMERCIAL', 
                   'GERENTE DE ALMOXARIFADO', 
                   'GERENTE DE COMPRAS', 
                   'GERENTE DE COMUNICACAO', 
                   'GERENTE DE CONTAS PESSOA FISICA E JURIDICA', 
                   'GERENTE DE DEPARTAMENTO PESSOAL', 
                   'GERENTE DE DESENVOLVIMENTO DE SISTEMAS', 
                   'GERENTE DE MARKETING', 
                   'GERENTE DE OPERACOES DE SERVICOS DE ASSISTENCIA TECNICA', 
                   'GERENTE DE OPERACOES DE TRANSPORTES', 
                   'GERENTE DE PESQUISA E DESENVOLVIMENTO (PD)', 
                   'GERENTE DE PRODUCAO DE TECNOLOGIA DA INFORMACAO', 
                   'GERENTE DE PRODUCAO E OPERACOES', 
                   'GERENTE DE PROJETOS E SERVICOS DE MANUTENCAO', 
                   'GERENTE DE RECURSOS HUMANOS', 
                   'GERENTE DE REDE', 
                   'GERENTE DE SERVICOS DE SAUDE', 
                   'GERENTE DE SERVICOS SOCIAIS', 
                   'GERENTE DE SUPORTE TECNICO DE TECNOLOGIA DA INFORMACAO', 
                   'GERENTE DE SUPRIMENTOS', 
                   'GERENTE DE VENDAS', 
                   'GERENTE FINANCEIRO', 
                   'GESTOR EM SEGURANCA', 
                   'GUARDA PORTUARIO', 
                   'GUARDACIVIL MUNICIPAL', 
                   'GUARDADOR DE VEICULOS', 
                   'HIGIENISTA OCUPACIONAL', 
                   'INSPETOR DE QUALIDADE', 
                   'INSTRUMENTADOR CIRURGICO', 
                   'INSTRUTOR DE APRENDIZAGEM E TREINAMENTO INDUSTRIAL', 
                   'INSTRUTOR DE CURSOS LIVRES', 
                   'JARDINEIRO', 
                   'JORNALISTA', 
                   'LABORATORISTA FOTOGRAFICO', 
                   'LAVADEIRO, EM GERAL', 
                   'LAVADOR DE ROUPAS', 
                   'LAVADOR DE ROUPAS A MAQUINA', 
                   'LAVADOR DE VEICULOS', 
                   'LEILOEIRO', 
                   'LIMPADOR A SECO, A MAQUINA', 
                   'LIMPADOR DE ROUPAS A SECO, A MAO', 
                   'MANICURE', 
                   'MANOBRADOR', 
                   'MARCENEIRO', 
                   'MASSOTERAPEUTA', 
                   'MECANICO DE MANUTENCAO DE MAQUINAS, EM GERAL', 
                   'MECANICO DE REFRIGERACAO', 
                   'MEDICO ACUPUNTURISTA', 
                   'MEDICO ALERGISTA E IMUNOLOGISTA', 
                   'MEDICO ANATOMOPATOLOGISTA', 
                   'MEDICO ANESTESIOLOGISTA', 
                   'MEDICO ANGIOLOGISTA', 
                   'MEDICO BRONCOESOFALOGISTA', 
                   'MEDICO CANCEROLOGISTA CIRURGICO', 
                   'MEDICO CANCEROLOGISTA PEDIATRICO', 
                   'MEDICO CARDIOLOGISTA', 
                   'MEDICO CARDIOLOGISTA INTERVENCIONISTA', 
                   'MEDICO CIRURGIAO CARDIOVASCULAR', 
                   'MEDICO CIRURGIAO DA MAO', 
                   'MEDICO CIRURGIAO DE CABECA E PESCOCO', 
                   'MEDICO CIRURGIAO DO APARELHO DIGESTIVO', 
                   'MEDICO CIRURGIAO GERAL', 
                   'MEDICO CIRURGIAO PEDIATRICO', 
                   'MEDICO CIRURGIAO PLASTICO', 
                   'MEDICO CIRURGIAO TORACICO', 
                   'MEDICO CITOPATOLOGISTA', 
                   'MEDICO CLINICO', 
                   'MEDICO COLOPROCTOLOGISTA', 
                   'MEDICO DA ESTRATEGIA DE SAUDE DA FAMILIA', 
                   'MEDICO DE FAMILIA E COMUNIDADE', 
                   'MEDICO DERMATOLOGISTA', 
                   'MEDICO DO TRABALHO', 
                   'MEDICO EM CIRURGIA VASCULAR', 
                   'MEDICO EM ENDOSCOPIA', 
                   'MEDICO EM MEDICINA DE TRAFEGO', 
                   'MEDICO EM MEDICINA INTENSIVA', 
                   'MEDICO EM MEDICINA NUCLEAR', 
                   'MEDICO EM MEDICINA PREVENTIVA E SOCIAL', 
                   'MEDICO EM RADIOLOGIA E DIAGNOSTICO POR IMAGEM', 
                   'MEDICO ENDOCRINOLOGISTA E METABOLOGISTA', 
                   'MEDICO FISIATRA', 
                   'MEDICO GASTROENTEROLOGISTA', 
                   'MEDICO GENERALISTA', 
                   'MEDICO GENETICISTA', 
                   'MEDICO GERIATRA', 
                   'MEDICO GINECOLOGISTA E OBSTETRA', 
                   'MEDICO HANSENOLOGISTA', 
                   'MEDICO HEMATOLOGISTA', 
                   'MEDICO HEMOTERAPEUTA', 
                   'MEDICO HIPERBARISTA', 
                   'MEDICO HOMEOPATA', 
                   'MEDICO INFECTOLOGISTA', 
                   'MEDICO LEGISTA', 
                   'MEDICO MASTOLOGISTA', 
                   'MEDICO NEFROLOGISTA', 
                   'MEDICO NEUROCIRURGIAO', 
                   'MEDICO NEUROFISIOLOGISTA CLINICO', 
                   'MEDICO NEUROLOGISTA', 
                   'MEDICO NUTROLOGISTA', 
                   'MEDICO OFTALMOLOGISTA', 
                   'MEDICO ONCOLOGISTA CLINICO', 
                   'MEDICO ORTOPEDISTA E TRAUMATOLOGISTA', 
                   'MEDICO OTORRINOLARINGOLOGISTA', 
                   'MEDICO PATOLOGISTA', 
                   'MEDICO PATOLOGISTA CLINICO MEDICINA LABORATORIAL', 
                   'MEDICO PEDIATRA', 
                   'MEDICO PNEUMOLOGISTA', 
                   'MEDICO PSIQUIATRA', 
                   'MEDICO RADIOLOGISTA INTERVENCIONISTA', 
                   'MEDICO RADIOTERAPEUTA', 
                   'MEDICO RESIDENTE', 
                   'MEDICO REUMATOLOGISTA', 
                   'MEDICO SANITARISTA', 
                   'MEDICO UROLOGISTA', 
                   'MEDICO VETERINARIO', 
                   'MERGULHADOR PROFISSIONAL (RASO E PROFUNDO)', 
                   'MESTRE (CONSTRUCAO CIVIL)', 
                   'MICROSCOPISTA', 
                   'MODELISTA DE ROUPAS', 
                   'MONITOR DE DEPENDENTE QUIMICO', 
                   'MOTOCICLISTA NO TRANSPORTE DE DOCUMENTOS E PEQUENOS VOLUMES', 
                   'MOTORISTA DE CAMINHAO (ROTAS REGIONAIS E INTERNACIONAIS)', 
                   'MOTORISTA DE CARRO DE PASSEIO', 
                   'MOTORISTA DE FURGAO OU VEICULO SIMILAR', 
                   'MOTORISTA DE ONIBUS RODOVIARIO', 
                   'MOTORISTA DE ONIBUS URBANO', 
                   'MOTORISTA DE TAXI', 
                   'MUSICO ARRANJADOR', 
                   'MUSICO INTERPRETE INSTRUMENTISTA', 
                   'MUSICO REGENTE', 
                   'MUSICOTERAPEUTA', 
                   'NATUROLOGO', 
                   'NEUROPSICOLOGO', 
                   'NUTRICIONISTA', 
                   'OPERADOR DE AUDIO DE CONTINUIDADE (RADIO)', 
                   'OPERADOR DE CAIXA', 
                   'OPERADOR DE CAMERA DE TELEVISAO', 
                   'OPERADOR DE CENTRAL DE RADIO', 
                   'OPERADOR DE COMPUTADOR (INCLUSIVE MICROCOMPUTADOR)', 
                   'OPERADOR DE MAQUINA DE FABRICACAO DE PRODUTOS DE HIGIENE E LIMPEZA (SABAO, SABONETE, DETERGENTE, ABSORVENTE, FRALDAS COTONETES E OUTROS)', 
                   'OPERADOR DE MAQUINAS FIXAS, EM GERAL', 
                   'OPERADOR DE RADIOCHAMADA', 
                   'OPERADOR DE SISTEMAS DE PROVA (ANALOGICO E DIGITAL)', 
                   'OPERADOR DE TELEMARKETING ATIVO', 
                   'OPERADOR DE TELEMARKETING ATIVO E RECEPTIVO', 
                   'OPERADOR DE TELEMARKETING RECEPTIVO', 
                   'OPERADOR DE TELEMARKETING TECNICO', 
                   'ORGANIZADOR DE EVENTO', 
                   'ORIENTADOR EDUCACIONAL', 
                   'ORTOPTISTA', 
                   'OUVIDOR', 
                   'PARTEIRA LEIGA', 
                   'PASSADOR DE ROUPAS EM GERAL', 
                   'PEDAGOGO', 
                   'PEDREIRO', 
                   'PEDREIRO DE EDIFICACOES', 
                   'PERFUMISTA', 
                   'PERFUSIONISTA', 
                   'PESQUISADOR EM BIOLOGIA DE MICROORGANISMOS E PARASITAS', 
                   'PINTOR A PINCEL E ROLO (EXCETO OBRAS E ESTRUTURAS METALICAS)', 
                   'PINTOR DE OBRAS', 
                   'PODOLOGO', 
                   'PORTEIRO DE EDIFICIOS', 
                   'PORTEIRO DE LOCAIS DE DIVERSAO', 
                   'PORTEIRO (HOTEL)', 
                   'PREPARADOR FISICO', 
                   'PROFESSOR DA EDUCACAO DE JOVENS E ADULTOS DO ENSINO FUNDAMENTAL (PRIMEIRA A QUARTA SERIE)', 
                   'PROFESSOR DE ALUNOS COM DEFICIENCIA FISICA', 
                   'PROFESSOR DE ALUNOS COM DEFICIENCIA MENTAL', 
                   'PROFESSOR DE ALUNOS COM DEFICIENCIA MULTIPLA', 
                   'PROFESSOR DE ALUNOS COM DEFICIENCIA VISUAL', 
                   'PROFESSOR DE ARTES NO ENSINO MEDIO', 
                   'PROFESSOR DE ARTES VISUAIS NO ENSINO SUPERIOR (ARTES PLASTICAS E MULTIMIDIA)', 
                   'PROFESSOR DE BIOLOGIA NO ENSINO MEDIO', 
                   'PROFESSOR DE CIENCIAS EXATAS E NATURAIS DO ENSINO FUNDAMENTAL', 
                   'PROFESSOR DE DANCA', 
                   'PROFESSOR DE EDUCACAO ARTISTICA DO ENSINO FUNDAMENTAL', 
                   'PROFESSOR DE EDUCACAO FISICA DO ENSINO FUNDAMENTAL', 
                   'PROFESSOR DE EDUCACAO FISICA NO ENSINO MEDIO', 
                   'PROFESSOR DE EDUCACAO FISICA NO ENSINO SUPERIOR', 
                   'PROFESSOR DE ENSINO SUPERIOR NA AREA DE PESQUISA EDUCACIONAL', 
                   'PROFESSOR DE ENSINO SUPERIOR NA AREA DE PRATICA DE ENSINO', 
                   'PROFESSOR DE FARMACIA E BIOQUIMICA', 
                   'PROFESSOR DE FISICA (ENSINO SUPERIOR)', 
                   'PROFESSOR DE FISIOTERAPIA', 
                   'PROFESSOR DE FONOAUDIOLOGIA', 
                   'PROFESSOR DE HISTORIA DO ENSINO FUNDAMENTAL', 
                   'PROFESSOR DE LINGUA E LITERATURA BRASILEIRA NO ENSINO MEDIO', 
                   'PROFESSOR DE LINGUA PORTUGUESA DO ENSINO FUNDAMENTAL', 
                   'PROFESSOR DE LINGUAS ESTRANGEIRAS MODERNAS', 
                   'PROFESSOR DE MATEMATICA DO ENSINO FUNDAMENTAL', 
                   'PROFESSOR DE MATEMATICA NO ENSINO MEDIO', 
                   'PROFESSOR DE MEDICINA', 
                   'PROFESSOR DE NIVEL MEDIO NA EDUCACAO INFANTIL', 
                   'PROFESSOR DE NIVEL MEDIO NO ENSINO FUNDAMENTAL', 
                   'PROFESSOR DE NIVEL MEDIO NO ENSINO PROFISSIONALIZANTE', 
                   'PROFESSOR DE NIVEL SUPERIOR DO ENSINO FUNDAMENTAL (PRIMEIRA A QUARTA SERIE)', 
                   'PROFESSOR DE NIVEL SUPERIOR NA EDUCACAO INFANTIL (QUATRO A SEIS ANOS)', 
                   'PROFESSOR DE NIVEL SUPERIOR NA EDUCACAO INFANTIL (ZERO A TRES ANOS)', 
                   'PROFESSOR DE NUTRICAO', 
                   'PROFESSOR DE ODONTOLOGIA', 
                   'PROFESSOR DE PSICOLOGIA DO ENSINO SUPERIOR', 
                   'PROFESSOR DE SOCIOLOGIA NO ENSINO MEDIO', 
                   'PROFESSOR DE TECNICAS DE ENFERMAGEM', 
                   'PROFESSOR DE TERAPIA OCUPACIONAL', 
                   'PROFESSOR INSTRUTOR DE ENSINO E APRENDIZAGEM EM SERVICOS', 
                   'PROFESSORES DE CURSOS LIVRES', 
                   'PROFISSIONAL DE EDUCACAO FISICA NA SAUDE', 
                   'PROGRAMADOR DE MULTIMIDIA', 
                   'PROGRAMADOR DE SISTEMAS DE INFORMACAO', 
                   'PROTETICO DENTARIO', 
                   'PSICANALISTA', 
                   'PSICOLOGO CLINICO', 
                   'PSICOLOGO DO TRABALHO', 
                   'PSICOLOGO DO TRANSITO', 
                   'PSICOLOGO EDUCACIONAL', 
                   'PSICOLOGO HOSPITALAR', 
                   'PSICOLOGO SOCIAL', 
                   'PSICOPEDAGOGO', 
                   'QUIMICO', 
                   'QUIROPRAXISTA', 
                   'RECEPCIONISTA DE CONSULTORIO MEDICO OU DENTARIO', 
                   'RECEPCIONISTA, EM GERAL', 
                   'RECREADOR', 
                   'RELACOES PUBLICAS', 
                   'REPRESENTANTE COMERCIAL AUTONOMO', 
                   'SANITARISTA', 
                   'SECRETARIA EXECUTIVA', 
                   'SECRETARIOEXECUTIVO', 
                   'SERRALHEIRO', 
                   'SERVENTE DE OBRAS', 
                   'SOCIOLOGO', 
                   'SOCORRISTA (EXCETO MEDICOS E ENFERMEIROS)', 
                   'SOLDADO DA POLICIA MILITAR', 
                   'SUPERVISOR ADMINISTRATIVO', 
                   'SUPERVISOR DA MANUTENCAO E REPARACAO DE VEICULOS PESADOS', 
                   'SUPERVISOR DE ALMOXARIFADO', 
                   'SUPERVISOR DE COBRANCA', 
                   'SUPERVISOR DE COMPRAS', 
                   'SUPERVISOR DE CONTROLE PATRIMONIAL', 
                   'SUPERVISOR DE DIGITACAO E OPERACAO', 
                   'SUPERVISOR DE ENSINO', 
                   'SUPERVISOR DE LAVANDERIA', 
                   'SUPERVISOR DE MANUTENCAO DE APARELHOS TERMICOS, DE CLIMATIZACAO E DE REFRIGERACAO', 
                   'SUPERVISOR DE MANUTENCAO ELETROMECANICA INDUSTRIAL, COMERCIAL E PREDIAL', 
                   'SUPERVISOR DE OPERACAO ELETRICA (GERACAO, TRANSMISSAO E DISTRIBUICAO DE ENERGIA ELETRICA)', 
                   'SUPERVISOR DE RECEPCIONISTAS', 
                   'SUPERVISOR DE TELEFONISTAS', 
                   'SUPERVISOR DE TELEMARKETING E ATENDIMENTO', 
                   'SUPERVISOR DE TESOURARIA', 
                   'SUPERVISOR DE TRANSPORTES', 
                   'SUPERVISOR DE VENDAS COMERCIAL', 
                   'SUPERVISOR DE VIGILANTES', 
                   'TECNICO AGRICOLA', 
                   'TECNICO AGROPECUARIO', 
                   'TECNICO DE ALIMENTOS', 
                   'TECNICO DE APOIO AO USUARIO DE INFORMATICA (HELPDESK)', 
                   'TECNICO DE APOIO EM PESQUISA E DESENVOLVIMENTO AGROPECUARIO FLORESTAL', 
                   'TECNICO DE APOIO EM PESQUISA E DESENVOLVIMENTO (EXCETO AGROPECUARIO E FLORESTAL)', 
                   'TECNICO DE COMUNICACAO DE DADOS', 
                   'TECNICO DE CONTABILIDADE', 
                   'TECNICO DE CONTROLE DE MEIO AMBIENTE', 
                   'TECNICO DE ENFERMAGEM', 
                   'TECNICO DE ENFERMAGEM DA ESTRATEGIA DE SAUDE DA FAMILIA', 
                   'TECNICO DE ENFERMAGEM DE TERAPIA INTENSIVA', 
                   'TECNICO DE ENFERMAGEM DO TRABALHO', 
                   'TECNICO DE ENFERMAGEM PSIQUIATRICA', 
                   'TECNICO DE GARANTIA DA QUALIDADE', 
                   'TECNICO DE IMOBILIZACAO ORTOPEDICA', 
                   'TECNICO DE LABORATORIO DE ANALISES FISICOQUIMICAS (MATERIAIS DE CONSTRUCAO)', 
                   'TECNICO DE LABORATORIO E FISCALIZACAO DESPORTIVA', 
                   'TECNICO DE LABORATORIO INDUSTRIAL', 
                   'TECNICO DE MANUTENCAO DE SISTEMAS E INSTRUMENTOS', 
                   'TECNICO DE MANUTENCAO ELETRICA', 
                   'TECNICO DE MANUTENCAO ELETRICA DE MAQUINA', 
                   'TECNICO DE MANUTENCAO ELETRONICA', 
                   'TECNICO DE OBRAS CIVIS', 
                   'TECNICO DE OPERACAO (QUIMICA, PETROQUIMICA E AFINS)', 
                   'TECNICO DE ORTOPEDIA', 
                   'TECNICO DE PLANEJAMENTO DE PRODUCAO', 
                   'TECNICO DE PLANEJAMENTO E PROGRAMACAO DA MANUTENCAO', 
                   'TECNICO DE REDE (TELECOMUNICACOES)', 
                   'TECNICO DE SANEAMENTO', 
                   'TECNICO DE TELECOMUNICACOES (TELEFONIA)', 
                   'TECNICO DE UTILIDADE (PRODUCAO E DISTRIBUICAO DE VAPOR, GASES, OLEOS, COMBUSTIVEIS, ENERGIA)', 
                   'TECNICO ELETRICISTA', 
                   'TECNICO ELETRONICO', 
                   'TECNICO EM ACUPUNTURA', 
                   'TECNICO EM ADMINISTRACAO', 
                   'TECNICO EM ELETROMECANICA', 
                   'TECNICO EM EQUIPAMENTO MEDICO HOSPITALAR', 
                   'TECNICO EM FARMACIA', 
                   'TECNICO EM HEMOTERAPIA', 
                   'TECNICO EM HISTOLOGIA', 
                   'TECNICO EM IMUNOBIOLOGICOS', 
                   'TECNICO EM LABORATORIO DE FARMACIA', 
                   'TECNICO EM MANUTENCAO DE EQUIPAMENTOS DE INFORMATICA', 
                   'TECNICO EM MANUTENCAO DE EQUIPAMENTOS E INSTRUMENTOS MEDICOHOSPITALARES', 
                   'TECNICO EM MANUTENCAO DE MAQUINAS', 
                   'TECNICO EM METODOS ELETROGRAFICOS EM ENCEFALOGRAFIA', 
                   'TECNICO EM METODOS GRAFICOS EM CARDIOLOGIA', 
                   'TECNICO EM NUTRICAO E DIETETICA', 
                   'TECNICO EM OPTICA E OPTOMETRIA', 
                   'TECNICO EM PATOLOGIA CLINICA', 
                   'TECNICO EM QUIROPRAXIA', 
                   'TECNICO EM RADIOLOGIA E IMAGENOLOGIA', 
                   'TECNICO EM REABILITACAO', 
                   'TECNICO EM SAUDE BUCAL', 
                   'TECNICO EM SAUDE BUCAL DA ESTRATEGIA DE SAUDE DA FAMILIA', 
                   'TECNICO EM SECRETARIADO', 
                   'TECNICO EM SEGURANCA NO TRABALHO', 
                   'TECNICO MECANICO (CALEFACAO, VENTILACAO E REFRIGERACAO)', 
                   'TECNICO QUIMICO', 
                   'TECNOLOGO EM ELETRONICA', 
                   'TECNOLOGO EM GESTAO ADMINISTRATIVO FINANCEIRA', 
                   'TECNOLOGO EM GESTAO DA TECNOLOGIA DA INFORMACAO', 
                   'TECNOLOGO EM GESTAO HOSPITALAR', 
                   'TECNOLOGO EM LOGISTICA DE TRANSPORTE', 
                   'TECNOLOGO EM MEIO AMBIENTE', 
                   'TECNOLOGO EM RADIOLOGIA', 
                   'TECNOLOGO EM SECRETARIADO ESCOLAR', 
                   'TECNOLOGO EM SEGURANCA DO TRABALHO', 
                   'TECNOLOGO OFTALMICO', 
                   'TELEFONISTA', 
                   'TELEOPERADOR', 
                   'TEOLOGO', 
                   'TERAPEUTA HOLISTICO', 
                   'TERAPEUTA OCUPACIONAL', 
                   'TESOUREIRO DE BANCO', 
                   'TRABALHADOR DA MANUTENCAO DE EDIFICACOES', 
                   'TRABALHADOR DE SERVICOS DE LIMPEZA E CONSERVACAO DE AREAS PUBLICAS', 
                   'TRABALHADOR DE TRATAMENTO DO LEITE E FABRICACAO DE LATICINIOS E AFINS', 
                   'TRATADOR DE ANIMAIS', 
                   'VIGIA', 
                   'VIGILANTE', 
                   'VISITADOR SANITARIO', 
                   'ZELADOR DE EDIFICIO', 
                   'ZOOTECNISTA' ]

# Solicita informacao do usuario
# basta digitar um fragmento da profissao.
# ex.: adm, saude, prog, rede ...
palavra = input('Qual profissao? ')

# Criando uma nova lista para receber o resultado da busca
new_lst_profissoes = []

# Procurar por 'palavra' nos itens da lista 'lst_profissoes'
for m in lst_profissoes:
    # Se encontrar, adiciona o item na nova lista...
    if re.search('{}'.format(palavra), m, re.I):
        new_lst_profissoes.append(m)

# nova lista serah mostrada com os itens adicionados
for n in new_lst_profissoes:
    # imprime cada item ...
    print( n )
